# Generated by Django 2.1.1 on 2018-09-09 21:26

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.TextField(max_length=2000)),
                ('purpose', models.TextField(max_length=5000)),
                ('description', models.TextField(max_length=10000)),
                ('location_city', models.CharField(max_length=255)),
                ('location_state', models.CharField(max_length=255)),
                ('location_country', models.CharField(max_length=255)),
                ('phone_p', models.CharField(max_length=50)),
                ('phone_s', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('created_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_ngos', to=settings.AUTH_USER_MODEL)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='modified_ngos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NGO_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.CharField(choices=[('C', 'Charitable'), ('S', 'Service'), ('P', 'Participatory'), ('E', 'Empowering')], max_length=1)),
                ('level', models.CharField(choices=[('COM', 'Community based'), ('CIT', 'City wide'), ('STA', 'State NGO'), ('NAT', 'National Ngo'), ('INT', 'International Ngo')], max_length=3)),
                ('activity', models.CharField(choices=[('O', 'Operational'), ('C', 'Campaigning'), ('OC', 'Both Operational & Campaigning'), ('PR', 'Public Relations'), ('PM', 'Project Management')], max_length=2)),
                ('staffing', models.CharField(choices=[('V', 'Volunteers'), ('P', 'Paid Staff'), ('VP', 'Both Volunteers & Paid Staff')], max_length=2)),
                ('fund', models.CharField(choices=[('H', 'High (>= US $ 1 Billion)'), ('M', 'Medium (>= US $ 1 Million)'), ('L', 'Low (< US $ 1 Million)')], max_length=1)),
                ('fund_acceptance_from', models.CharField(choices=[('G', 'Government'), ('C', 'Firms / Companies / Organizations'), ('I', 'Individual'), ('N', 'Other NGOs')], max_length=1)),
                ('legal_status', models.CharField(choices=[('UVA', 'Unincorporated & Voluntary Association'), ('TCF', 'Trust, Charities & Foundations'), ('CNF', 'Companies not just for profit'), ('NPL', 'Entities formed or registered under special NGO or Non Profit Laws')], max_length=3)),
                ('overhead_cost', models.PositiveSmallIntegerField()),
                ('ngo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.NGO')),
            ],
        ),
        migrations.CreateModel(
            name='NGO_Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_mobile_p', models.BooleanField(default=False)),
                ('v_mobile_s', models.BooleanField(default=False)),
                ('v_email', models.BooleanField(default=False)),
                ('v_website', models.BooleanField(default=False)),
                ('modified_by', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verified_ngos', to=settings.AUTH_USER_MODEL)),
                ('ngo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='core.NGO')),
            ],
        ),
    ]
