# Generated by Django 2.1.1 on 2018-09-09 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo_verification',
            old_name='v_mobile_p',
            new_name='v_phone_p',
        ),
        migrations.RenameField(
            model_name='ngo_verification',
            old_name='v_mobile_s',
            new_name='v_phone_s',
        ),
    ]
