# Generated by Django 2.1.1 on 2018-09-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180910_0328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo',
            old_name='phone_p',
            new_name='phone_primary',
        ),
        migrations.RenameField(
            model_name='ngo',
            old_name='phone_s',
            new_name='phone_secondary',
        ),
        migrations.RenameField(
            model_name='ngo_verification',
            old_name='v_phone_p',
            new_name='verified_phone_primary',
        ),
        migrations.RenameField(
            model_name='ngo_verification',
            old_name='v_phone_s',
            new_name='verified_phone_secondary',
        ),
    ]
