# Generated by Django 2.1.1 on 2018-09-09 23:01

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180910_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='created_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='CreatedNgo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='description',
            field=models.TextField(help_text='Description of the Ngo | 10,000 characters max | 300 characters min', max_length=10000),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='email',
            field=models.EmailField(help_text='Email of the Ngo | 254 characters max (RFC 2821)', max_length=254),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='location_city',
            field=models.CharField(help_text='Location of the Ngo | 255 characters max | City', max_length=255),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='location_country',
            field=models.CharField(help_text='Location of the Ngo | 255 characters max | Country', max_length=255),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='location_state',
            field=models.CharField(help_text='Location of the Ngo | 255 characters max | State', max_length=255),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ModifiedNgo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='name',
            field=models.TextField(help_text='Name of the Ngo | 2,000 characters max | 2 characters min', max_length=2000),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='phone_primary',
            field=models.CharField(help_text='Phone Number of the Ngo | 50 characters max | Primary Phone Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='phone_secondary',
            field=models.CharField(help_text='Phone Number of the Ngo | 50 characters max | Secondary Phone Number', max_length=50),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='purpose',
            field=models.TextField(help_text='Purpose of the Ngo | 5,000 characters max | 50 characters min', max_length=5000),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='website',
            field=models.URLField(help_text='Website of the Ngo | 200 characters max'),
        ),
        migrations.AlterField(
            model_name='ngo_detail',
            name='fund_acceptance_from',
            field=models.CharField(choices=[('G', 'Government'), ('C', 'Firms / Companies / Organizations'), ('I', 'Individual'), ('N', 'Other Ngos')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ngo_detail',
            name='legal_status',
            field=models.CharField(choices=[('UVA', 'Unincorporated & Voluntary Association'), ('TCF', 'Trust, Charities & Foundations'), ('CNF', 'Companies not just for profit'), ('NPL', 'Entities formed or registered under special Ngo or Non Profit Laws')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ngo_detail',
            name='level',
            field=models.CharField(choices=[('COM', 'Community based'), ('CIT', 'City wide'), ('STA', 'State Ngo'), ('NAT', 'National Ngo'), ('INT', 'International Ngo')], max_length=3),
        ),
        migrations.AlterField(
            model_name='ngo_detail',
            name='ngo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.Ngo'),
        ),
        migrations.AlterField(
            model_name='ngo_verification',
            name='modified_by',
            field=cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='VerifiedNgo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ngo_verification',
            name='ngo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Verification', to='core.Ngo'),
        ),
    ]
