# Generated by Django 2.1.1 on 2018-09-09 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180910_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo_detail',
            name='ngo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.Ngo'),
        ),
        migrations.AlterField(
            model_name='ngo_verification',
            name='ngo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Verification', to='core.Ngo'),
        ),
    ]
